name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js 10.x # 配置Node环境
        uses: actions/setup-node@v1 # 配置脚本来自 https://github.com/actions/setup-node
        with:
          node-version: "10.x"
      
      - name: Setup Hexo env
        run: npm install -g @vue/cli-service-global

      - name: npm install, build
        run: |
          npm install
          npm run build

      - name: Release Github Pages
        uses: igolopolosov/github-action-release-github-pages@master
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.AURORACI_TOKEN }}
          GITHUB_PAGES_REPO_AUTHOR: starsky1
          GITHUB_PAGES_REPO_NAME: starsky1.github.io
          GITHUB_PAGES_RELEASE_BRANCH: master
          PROJECT_BUILD_FOLDER: dist
          # GITHUB_PAGES_CLEANUP_SCRIPT: "rm bundle* && rm index.html"