name: Aurora CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js 10.x # 配置Node环境
        uses: actions/setup-node@v1 # 配置脚本来自 https://github.com/actions/setup-node
        with:
          node-version: "10.x"
      
      - name: Setup vue-cli env
        run: npm install -g @vue/cli-service-global

      - name: npm install, build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          repo: starsky1.github.io
          target_branch: master
          build_dir: dist
        env:
          GH_PAT: ${{ secrets.AURORACI_TOKEN }}